### ISSUE TITLE
Bug In 1.3.1

### ISSUE THREAD

**Issue by jackjangri** [Stapo/Lite-DayZ-Private-Server#2]
When Install Extra 
It Not Work

**Comment by Stapo** [comment]
http://opendayz.net/index.php?threads/how-to-post-a-support-ticket.7623/

That applies for github aswell :)

**Comment by jackjangri** [comment]
## FOR GENERAL SUPPORT

Mod Name: DayZ Thirsk Winter

Extras: combo4

Problem Description: It Close When Enter combo4

**Comment by Stapo** [comment]
thanks, ill fix it for the next update

**Comment by jackjangri** [comment]
OK. I Like U Server.
