### ISSUE TITLE
DayZ/DayZ+/DayZ 2017 MPMissions issue

### ISSUE THREAD

**Issue by UBERKalti** [Stapo/Lite-DayZ-Private-Server#3]
Mod Name:
Dayz/Dayz+/Dayz2017

Extras:
DayZ: combo1
DayZ+: none
DayZ 2017: none.

Problem Description:
When having all three mods installed, the last mod installed will have overwritten the mission-file of the two previously installed mods because they all have the same name (dayz_1.Chernarus.pbo) While each mod in fact requires it's own specific mission-file.

**Comment by Stapo** [comment]
https://github.com/Stapo/Lite-Repo/commit/8bb8ea3ca46f12b3bc9df022bbff3852316f3eb8
