### ISSUE TITLE
No Zombies and no Loot

### ISSUE THREAD

**Issue by hsswatte** [Stapo/Lite-DayZ-Private-Server#9]
Hi, i am running a DayZ Lite Panthera Server (DayZCode 1.7.6.1, Panthera 1.8 and Arma 102591) and i have the following problem:

When i fly across the Map with a chopper no Zombies would spawn due me flying in the Chopper. Also when i land and get out - no zombies and no loot all around. When i log out and log in again - zombies and loot start spawning. But nothing if you just fly there and get out of the vehicle.

Thanks for your help.

waTTe

**Comment by Stapo** [comment]
Hi, that problem is CLIENT related and therefore not something I can fix.
